import { useMemo, useState } from 'react';
import { CalendarDays, Clock3, MapPin, ChevronLeft, ChevronRight, CheckCircle2 } from 'lucide-react';
import { PortalShell, STUDENT } from '@/components/portal/PortalComponents';
import { format, startOfMonth, endOfMonth, eachDayOfInterval, isSameDay } from 'date-fns';

const shifts = { '2026-09-18': ['08:00 AM – 04:00 PM'], '2026-09-19': ['08:00 AM – 04:00 PM'], '2026-09-21': ['10:00 AM – 04:00 PM'], '2026-09-23': ['08:00 AM – 04:00 PM'], '2026-09-25': ['08:00 AM – 12:00 PM'] };
export default function SchedulePage() {
  const [selected, setSelected] = useState(new Date()); const month = new Date(2026,8,1); const days=eachDayOfInterval({start:startOfMonth(month),end:endOfMonth(month)}); const leading=(month.getDay()+6)%7; const key=format(selected,'yyyy-MM-dd');
  const selectedShifts=shifts[key]||[];
  return <PortalShell><main className="px-5 py-7 md:px-8 md:py-8"><div className="mb-6"><p className="mb-3 inline-flex rounded-full bg-[#162c4d] px-3 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-white">Student Schedule</p><h1 className="serif text-4xl text-[#10253f]">Library Assistant Shift Management</h1><p className="mt-2 max-w-2xl text-sm text-[#52708b]">View your assigned shifts, daily activity and approved schedule changes in one place.</p></div>
<div className="grid gap-6 xl:grid-cols-[1fr_320px]"><section className="rounded-xl bg-[#f4f8fb] p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-[#10253f]">September 2026</h2><p className="text-xs text-[#718196]">Monthly shift calendar</p></div><div className="flex gap-2"><button className="rounded-lg border bg-white p-2 text-[#52708b]"><ChevronLeft size={16}/></button><button className="rounded-lg border bg-white p-2 text-[#52708b]"><ChevronRight size={16}/></button></div></div><div className="mt-5 grid grid-cols-7 gap-px overflow-hidden rounded-lg border border-[#dce5ec] bg-[#dce5ec]"><div className="col-span-7 grid grid-cols-7 bg-white">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><div key={d} className="p-2 text-center text-[10px] font-bold uppercase text-[#8ca0b2]">{d}</div>)}</div>{Array.from({length:leading}).map((_,i)=><div key={'lead'+i} className="min-h-24 bg-[#f8fafc]"/>)}{days.map(day=>{const k=format(day,'yyyy-MM-dd'); const has=!!shifts[k]; return <button key={k} onClick={()=>setSelected(day)} className={`min-h-24 bg-white p-2 text-left align-top ${isSameDay(day,selected)?'ring-2 ring-inset ring-[#1f70d0]':''}`}><span className={`grid size-7 place-items-center rounded-full text-xs font-bold ${isSameDay(day,selected)?'bg-[#1f70d0] text-white':'text-[#385570]'}`}>{format(day,'d')}</span>{has&&<span className="mt-3 block rounded-md bg-[#e7f1fa] px-1.5 py-1 text-[9px] font-bold text-[#1f70d0]">Shift</span>}</button>})}</div></section>
<aside className="space-y-5"><div className="rounded-xl bg-white p-5 shadow-[0_3px_8px_rgba(53,91,121,.08)]"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[#e7f1fa] text-[#1f70d0]"><CalendarDays size={18}/></span><div><p className="text-xs font-bold uppercase tracking-[.08em] text-[#8ca0b2]">Selected day</p><h2 className="mt-1 font-bold text-[#10253f]">{format(selected,'EEEE, MMM d')}</h2></div></div>{selectedShifts.length?<div className="mt-5 space-y-3">{selectedShifts.map(s=><div key={s} className="rounded-lg bg-[#f4f8fb] p-3"><p className="flex items-center gap-2 text-sm font-bold text-[#243e5b]"><Clock3 size={14}/>{s}</p><p className="mt-1 flex items-center gap-2 text-xs text-[#718196]"><MapPin size={13}/>TUT Library</p></div>)}</div>:<p className="mt-5 text-sm text-[#718196]">No shift assigned for this date.</p>}</div><div className="rounded-xl bg-[#f4f8fb] p-5"><p className="text-sm font-bold text-[#10253f]">Schedule notes</p><ul className="mt-3 space-y-3 text-xs leading-5 text-[#5f7185]"><li className="flex gap-2"><CheckCircle2 size={14} className="mt-0.5 shrink-0 text-[#22b78b]"/>Approved leave and swaps are reflected here.</li><li className="flex gap-2"><Clock3 size={14} className="mt-0.5 shrink-0 text-[#1f70d0]"/>Arrive 10 minutes before your shift starts.</li></ul></div></aside></div></main></PortalShell>;
}
