import { useState } from 'react';
import { format } from 'date-fns';
import { RefreshCw, Clock3, FileText, Info, Check, CheckCircle2, ChevronRight } from 'lucide-react';
import { useLocation } from 'wouter';
import { PortalShell, DatePicker, FieldLabel, SuggestionBox, BackButton } from '@/components/portal/PortalComponents';
import { useRequests } from '@/context/RequestsContext';

const CURRENT_SHIFTS = [
  { key: 'sep19', date: 'September 19, 2026', time: '08:00 AM – 04:00 PM' },
  { key: 'sep21', date: 'September 21, 2026', time: '08:00 AM – 04:00 PM' },
];
export default function ShiftSwapPage() {
  const [, setLocation] = useLocation(); const { addRequest } = useRequests();
  const [shift, setShift] = useState('sep19'); const [colleague, setColleague] = useState(''); const [newDate, setNewDate] = useState(); const [reason, setReason] = useState(''); const [errors, setErrors] = useState({});
  const submit = e => { e.preventDefault(); const next={}; if(!colleague.trim()) next.colleague='Enter a colleague to swap with.'; if(!newDate) next.newDate='Select a future date in this month.'; setErrors(next); if(Object.keys(next).length)return; addRequest({
      type: `Shift Swap – ${colleague.trim()}`,
      replacement: colleague.trim(),
      dateRange: format(newDate, 'MMM d, yyyy'),
      detail: reason.trim() || 'Shift swap requested with an eligible colleague.',
      reason: reason.trim(),
      currentShift: CURRENT_SHIFTS.find((item) => item.key === shift),
    }); setLocation('/dashboard'); };
  return <PortalShell><main className="px-5 py-7 md:px-8 md:py-8"><BackButton href="/dashboard/request">Back to Request Leave</BackButton><p className="mb-3 inline-flex rounded-full bg-[#162c4d] px-3 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-white">Scheduling Management</p><h1 className="serif text-4xl text-[#10253f]">Shift Swapping Request</h1><p className="mt-2 max-w-xl text-sm text-[#52708b]">Need to change your schedule? Use this form to request a shift swap with another eligible team member. Both parties must agree before final administrative approval.</p>
<form onSubmit={submit} className="mt-6 rounded-xl bg-white p-5 shadow-[0_3px_8px_rgba(53,91,121,.08)] md:p-6"><div className="flex items-center gap-3 border-b border-[#e2eaf1] pb-5"><span className="grid size-9 place-items-center rounded-lg bg-[#e7f1fa] text-[#1f70d0]"><RefreshCw size={18}/></span><div><h2 className="text-lg font-bold text-[#10253f]">New Swap Request</h2><p className="text-sm text-[#52708b]">Fill in the details for your proposed shift exchange.</p></div></div>
<div className="mt-6"><p className="mb-3 flex items-center gap-1.5 text-xs font-bold uppercase tracking-[.08em] text-[#8ca0b2]"><span className="inline-block h-3.5 w-1 rounded-full bg-[#1f70d0]"/>1. Select Your Current Shift</p><div className="grid gap-3 sm:grid-cols-2">{CURRENT_SHIFTS.map(s=><button type="button" key={s.key} onClick={()=>setShift(s.key)} className={`focus-ring flex items-center justify-between rounded-lg border px-4 py-3 text-left ${shift===s.key?'border-[#1f70d0] bg-[#e7f1fa]':'border-[#d0e0ea] hover:border-[#9cc0dd]'}`}><span><span className="block text-sm font-bold text-[#243e5b]">{s.date}</span><span className="mt-0.5 flex items-center gap-1.5 text-xs text-[#71869a]"><Clock3 size={12}/>{s.time}</span></span>{shift===s.key&&<span className="grid size-5 place-items-center rounded-full bg-[#1f70d0] text-white"><Check size={12}/></span>}</button>)}</div></div>
<div className="mt-7"><p className="mb-3 flex items-center gap-1.5 text-xs font-bold uppercase tracking-[.08em] text-[#8ca0b2]"><span className="inline-block h-3.5 w-1 rounded-full bg-[#1f70d0]"/>2. Proposed Swap Details</p><div className="grid gap-5 sm:grid-cols-2"><label><FieldLabel required icon={<FileText size={14} className="text-[#8aa0b2]"/>}>Target Colleague</FieldLabel><input value={colleague} onChange={e=>setColleague(e.target.value)} placeholder="Search by name or student number..." className={`focus-ring w-full rounded-lg border bg-[#fbfdfe] px-3.5 py-3 text-sm text-[#243e5b] outline-none placeholder:text-[#9baebe] ${errors.colleague?'border-[#d05b48]':'border-[#cfdee9] focus:border-[#1f70d0]'}`}/><p className="mt-1.5 text-xs italic text-[#8aa0b2]">Start typing to see eligible team members for this role.</p>{errors.colleague&&<p className="mt-1 text-xs font-medium text-[#c54f43]">{errors.colleague}</p>}</label><DatePicker value={newDate} onChange={setNewDate} label="New Date / Shift" error={errors.newDate} helper="Only future dates in the current month can be selected."/></div><div className="mt-5"><label><FieldLabel required icon={<FileText size={14} className="text-[#8aa0b2]"/>}>Reason for Swap</FieldLabel><textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Example: I have a medical appointment and would like to exchange this shift with an available colleague." className="focus-ring w-full rounded-lg border border-[#cfdee9] bg-[#fbfdfe] px-3.5 py-3 text-sm text-[#243e5b] outline-none placeholder:text-[#9baebe] focus:border-[#1f70d0]"/></label><SuggestionBox suggestions={["Medical appointment", "Family commitment", "Academic timetable conflict", "Transport or scheduling issue"]}/></div></div>
<div className="mt-6 flex items-start gap-3 rounded-lg border border-[#d0e0ea] bg-[#f4f8fb] p-4"><Info size={18} className="mt-0.5 shrink-0 text-[#1f70d0]"/><div><p className="text-sm font-bold text-[#243e5b]">Swap Policy Notice</p><p className="mt-1 text-xs leading-5 text-[#71869a]">All swaps are subject to department lead approval. Swaps cannot exceed weekly hour limits (40h) and must maintain role coverage standards.</p></div></div>
<div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[#e2eaf1] pt-6"><span className="flex items-center gap-1.5 text-xs font-semibold text-[#8ca0b2]"><CheckCircle2 size={14}/>Draft is kept while you complete the form.</span><div className="flex gap-3"><button type="button" onClick={()=>setLocation('/dashboard/request')} className="focus-ring rounded-lg bg-[#d05b48] px-6 py-2.5 text-sm font-bold text-white">Cancel</button><button type="submit" className="focus-ring flex items-center gap-2 rounded-lg bg-[#1f70d0] px-6 py-2.5 text-sm font-bold text-white shadow-[0_4px_0_#1555aa]">Submit Swap Request<ChevronRight size={16}/></button></div></div></form></main></PortalShell>;
}
