function downloadBlob(content, filename, type) {
  const blob = content instanceof Blob ? content : new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function xmlEscape(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function crc32(bytes) {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i += 1) {
    crc ^= bytes[i];
    for (let j = 0; j < 8; j += 1) {
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function u16(value) {
  return new Uint8Array([value & 255, (value >>> 8) & 255]);
}

function u32(value) {
  return new Uint8Array([
    value & 255,
    (value >>> 8) & 255,
    (value >>> 16) & 255,
    (value >>> 24) & 255,
  ]);
}

function concatBytes(parts) {
  const size = parts.reduce((total, part) => total + part.length, 0);
  const output = new Uint8Array(size);
  let offset = 0;
  parts.forEach((part) => {
    output.set(part, offset);
    offset += part.length;
  });
  return output;
}

function zipStore(files) {
  const encoder = new TextEncoder();
  const localParts = [];
  const centralParts = [];
  let offset = 0;

  files.forEach(({ name, content }) => {
    const nameBytes = encoder.encode(name);
    const data = encoder.encode(content);
    const crc = crc32(data);
    const localHeader = concatBytes([
      new Uint8Array([0x50, 0x4b, 0x03, 0x04]),
      u16(20), u16(0x0800), u16(0), u16(0), u16(0), u32(crc), u32(data.length), u32(data.length),
      u16(nameBytes.length), u16(0), nameBytes,
    ]);
    localParts.push(localHeader, data);

    const centralHeader = concatBytes([
      new Uint8Array([0x50, 0x4b, 0x01, 0x02]),
      u16(20), u16(20), u16(0x0800), u16(0), u16(0), u16(0), u32(crc), u32(data.length), u32(data.length),
      u16(nameBytes.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset), nameBytes,
    ]);
    centralParts.push(centralHeader);
    offset += localHeader.length + data.length;
  });

  const centralDirectory = concatBytes(centralParts);
  const localDirectory = concatBytes(localParts);
  const end = concatBytes([
    new Uint8Array([0x50, 0x4b, 0x05, 0x06]),
    u16(0), u16(0), u16(files.length), u16(files.length), u32(centralDirectory.length), u32(localDirectory.length), u16(0),
  ]);
  return concatBytes([localDirectory, centralDirectory, end]);
}

function makeDocx(rows, title) {
  const paragraphs = [
    `<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="32"/></w:rPr><w:t>${xmlEscape(title)}</w:t></w:r></w:p>`,
    `<w:p><w:r><w:t>Generated by StudentAssist Performance Reports</w:t></w:r></w:p>`,
    `<w:p><w:r><w:t>Report period: ${xmlEscape(title.replace(/^Performance Reports\s*[—-]?\s*/, ''))}</w:t></w:r></w:p>`,
    `<w:p><w:r><w:t>Report date: ${xmlEscape(new Date().toLocaleDateString('en-ZA'))}</w:t></w:r></w:p>`,
  ];
  rows.forEach((row) => {
    paragraphs.push(`<w:p><w:r><w:rPr><w:b/></w:rPr><w:t>${xmlEscape(row.name)}</w:t></w:r></w:p>`);
    paragraphs.push(`<w:p><w:r><w:t>Hours worked: ${xmlEscape(row.hours)} | Total requests: ${xmlEscape(row.requests)} | ${xmlEscape(row.site)} | ${xmlEscape(row.days)} shifts</w:t></w:r></w:p>`);
    if (row.shiftDetails) paragraphs.push(`<w:p><w:r><w:t>Shift details: ${xmlEscape(row.shiftDetails)}</w:t></w:r></w:p>`);
  });

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs.join('')}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="900" w:right="900" w:bottom="900" w:left="900"/></w:sectPr></w:body></w:document>`;
  const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`;
  const rels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;
  const docRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>`;

  return zipStore([
    { name: '[Content_Types].xml', content: contentTypes },
    { name: '_rels/.rels', content: rels },
    { name: 'word/document.xml', content: documentXml },
    { name: 'word/_rels/document.xml.rels', content: docRels },
  ]);
}

function makeExcelXml(rows, title) {
  const headers = ['Report Period', 'Student Assistant', 'Hours Worked', 'Total Requests', 'Site', 'Days', 'Shift Details'];
  const tableRows = [
    `<Row><Cell><Data ss:Type="String">${xmlEscape(title)}</Data></Cell></Row>`,
    `<Row>${headers.map((h) => `<Cell><Data ss:Type="String">${xmlEscape(h)}</Data></Cell>`).join('')}</Row>`,
    ...rows.map((row) => `<Row><Cell><Data ss:Type="String">${xmlEscape(title.replace(/^Performance Reports\s*[—-]?\s*/, ''))}</Data></Cell><Cell><Data ss:Type="String">${xmlEscape(row.name)}</Data></Cell><Cell><Data ss:Type="String">${xmlEscape(row.hours)}</Data></Cell><Cell><Data ss:Type="Number">${Number(row.requests) || 0}</Data></Cell><Cell><Data ss:Type="String">${xmlEscape(row.site)}</Data></Cell><Cell><Data ss:Type="Number">${Number(row.days) || 0}</Data></Cell><Cell><Data ss:Type="String">${xmlEscape(row.shiftDetails || '')}</Data></Cell></Row>`),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Performance Report"><Table>${tableRows.join('')}</Table></Worksheet></Workbook>`;
}

function pdfEscape(value) {
  return String(value ?? '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function makePdf(rows, title) {
  const pages = [];
  const lines = [
    title,
    'StudentAssist Performance Report',
    `Generated: ${new Date().toLocaleDateString('en-ZA')}`,
    '',
    'Report period: ' + title.replace(/^Performance Reports\s*[—-]?\s*/, ''),
    'Student Assistant | Hours | Requests | Site | Shifts',
    ...rows.map((row) => `${row.name} | ${row.hours} | ${row.requests} | ${row.site} | ${row.days}`),
    ...rows.flatMap((row) => row.shiftDetails ? [`Shift details — ${row.name}: ${row.shiftDetails}`] : []),
  ];
  for (let i = 0; i < lines.length; i += 28) pages.push(lines.slice(i, i + 28));

  const objects = [];
  objects.push('<< /Type /Catalog /Pages 2 0 R >>');
  const pageObjectNumbers = [];
  let nextObject = 5;
  pages.forEach(() => { pageObjectNumbers.push(nextObject); nextObject += 2; });
  objects.push(`<< /Type /Pages /Kids [${pageObjectNumbers.map((n) => `${n} 0 R`).join(' ')}] /Count ${pages.length} >>`);
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  objects.push('<< /Producer (StudentAssist) >>');

  pages.forEach((pageLines, pageIndex) => {
    const pageNumber = pageObjectNumbers[pageIndex];
    const contentNumber = pageNumber + 1;
    const commands = ['BT', '/F1 10 Tf', '40 760 Td'];
    pageLines.forEach((line, lineIndex) => {
      if (lineIndex === 0) commands.push('/F1 16 Tf');
      else if (lineIndex === 3) commands.push('/F1 10 Tf');
      else if (lineIndex > 0) commands.push('/F1 10 Tf');
      commands.push(`(${pdfEscape(line)}) Tj`, '0 -22 Td');
    });
    commands.push('ET');
    const stream = commands.join('\n');
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentNumber} 0 R >>`);
    objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
  });

  const chunks = ['%PDF-1.4\n%\u00e2\u00e3\u00cf\u00d3\n'];
  const offsets = [0];
  let position = chunks[0].length;
  objects.forEach((obj, index) => {
    offsets[index + 1] = position;
    const chunk = `${index + 1} 0 obj\n${obj}\nendobj\n`;
    chunks.push(chunk);
    position += chunk.length;
  });
  const xrefOffset = position;
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i += 1) xref += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  chunks.push(xref, trailer);
  return new TextEncoder().encode(chunks.join(''));
}

export function exportPerformanceReport(format, rows, title = 'Performance Reports') {
  const safeDate = new Date().toISOString().slice(0, 10);
  if (format === 'csv') {
    const header = 'Report Period,Student Assistant,Hours Worked,Total Requests,Site,Days,Shift Details';
    const periodLine = title.replace(/^Performance Reports\s*[—-]?\s*/, '');
    const body = rows.map((row) => [periodLine, row.name, row.hours, row.requests, row.site, row.days, row.shiftDetails || ''].map((value) => `"${String(value ?? '').replace(/"/g, '""')}"`).join(','));
    downloadBlob([header, ...body].join('\n'), `studentassist-performance-${safeDate}.csv`, 'text/csv;charset=utf-8');
    return;
  }
  if (format === 'excel') {
    const xml = makeExcelXml(rows, title);
    downloadBlob(xml, `studentassist-performance-${safeDate}.xls`, 'application/vnd.ms-excel');
    return;
  }
  if (format === 'docx') {
    const bytes = makeDocx(rows, title);
    downloadBlob(new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }), `studentassist-performance-${safeDate}.docx`);
    return;
  }
  if (format === 'pdf') {
    const bytes = makePdf(rows, title);
    downloadBlob(new Blob([bytes], { type: 'application/pdf' }), `studentassist-performance-${safeDate}.pdf`);
  }
}
